RD-5834-define-credentials-in-azure-plugin-yaml
cloudify-cosmo/cloudify-azure-plugin pull request #258
Opened 2022-11-14 09:26 UTC by Nelynehemia

2022-11-14 16:11 UTC, EarthmanT requested changes

2022-11-14 16:11 UTC, EarthmanT commented on cloudify_azure/utils.py
> +    properties.update(other_properties)
I prefer that we will override other properties with properties. Order of importance is:
1. Client Config from Node Props
2. Client Config from Plugin Props
That means that we first get plugin props client config and then if there is a client config from node props, we override the first with that.

```suggestion
    other_properties.update(properties)
```

2022-11-23 14:39 UTC, ahmadiesa-abu commented on cloudify_azure/workflows/tests/test_discover.py
> +        print
let's remove this print from here

2022-11-23 14:40 UTC, ahmadiesa-abu commented on cloudify_azure/utils.py
> +        azure_config.update(final_client_config)
here we don't want to override the node level properties from the plugin properties level , it should be the other way around [ we can override the plugin properties from the node level ]

2022-11-23 14:42 UTC, ahmadiesa-abu commented
and one more thing , we need to bump the version after fixing all the tests [ and change log ]

2022-11-29 16:18 UTC, EarthmanT commented on cloudify_azure/utils.py
> +        final_client_config.update(azure_config)
We should double check that we are not overwriting values with empty ones. For example, let's say we have this:

```
azure_config = {
  'key': None,
  'key2': 'foo'
}

client_config = {
  'key': 'foobar',
}

```

Then `{'key': 'foobar'}` will be overwritten by `{'key': None}`. This is not what we want.

2022-12-04 16:32 UTC, merged